---
# tasks file for ant.wordpress
- name: Get Wordpress checksum
  uri: url=https://wordpress.org/latest.zip.sha1 return_content=true
  register: wp_checksum
- name: Download Wordpress
  get_url: url=https://wordpress.org/latest.zip dest=/tmp/wordpress.zip checksum="sha1:{{wp_checksum.content}}" 
- name: Unzip Wordpress
  unarchive: src=/tmp/wordpress.zip dest=/tmp copy=no creates=/tmp/wordpress/wp-settings.php
- name: Create project folder
  file: dest=/var/www/{{wp_domain}} state=directory
- name: Copy Wordpress files
  command: cp -a /tmp/wordpress/. /var/www/{{wp_domain}} creates=/var/www/{{wp_domain}}/wp-settings.php
- name: Create Wordpress database
  mysql_db: name="{{database_name}}" state=present
- name: Create Wordpress database user
  mysql_user: name="{{database_user}}" host=localhost password="{{database_password}}" priv="{{database_name}}.*:ALL"
- name: Create wp-config
  template: src=wp-config.j2 dest=/var/www/{{wp_domain}}/wp-config.php
- name: Does the database exist ?
  command: mysql -u root {{database_name}} -e "SELECT ID FROM {{database_name}}.wp_users LIMIT 1;"
  register: db_exist
  ignore_errors: true
  changed_when: false
- name: Copy Wordpress database
  template: src=wp-database.j2 dest=/tmp/wp-database.sql
  when: db_exist.rc > 0
- name: Import Wordpress database
  mysql_db: target=/tmp/wp-database.sql state=import name="{{database_name}}"
  when: db_exist.rc > 0
